[2022-11-20 11:50:20,576] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: first_dag.second_function_execute 2022-11-19T00:00:00+00:00 [queued]>
[2022-11-20 11:50:20,596] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: first_dag.second_function_execute 2022-11-19T00:00:00+00:00 [queued]>
[2022-11-20 11:50:20,621] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 11:50:20,643] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-11-20 11:50:20,644] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 11:50:20,656] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): second_function_execute> on 2022-11-19T00:00:00+00:00
[2022-11-20 11:50:20,660] {standard_task_runner.py:52} INFO - Started process 3967 to run task
[2022-11-20 11:50:20,667] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'second_function_execute', '2022-11-19T00:00:00+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpaajur9ld', '--error-file', '/tmp/tmprw72yud5']
[2022-11-20 11:50:20,668] {standard_task_runner.py:77} INFO - Job 14: Subtask second_function_execute
[2022-11-20 11:50:20,728] {logging_mixin.py:109} INFO - Running <TaskInstance: first_dag.second_function_execute 2022-11-19T00:00:00+00:00 [running]> on host c451c373dc68
[2022-11-20 11:50:20,794] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=second_function_execute
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T00:00:00+00:00
[2022-11-20 11:50:20,805] {logging_mixin.py:109} INFO - i am in second function got value :first function execute says hello from function_1
[2022-11-20 11:50:20,806] {python.py:151} INFO - Done. Returned value was: None
[2022-11-20 11:50:20,820] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=second_function_execute, execution_date=20221119T000000, start_date=20221120T115020, end_date=20221120T115020
[2022-11-20 11:50:20,884] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-11-20 11:50:20,909] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
